apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hello-app.fullname" . }}
spec:
  endpoints:
  - path: /metrics
    port: http
    interval: 15s 
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
